# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import pandas as p
import numpy as n

In [2]:
#Load given dataset
data = p.read_csv("combined_stock_data.csv")

In [3]:
import warnings
warnings.filterwarnings('ignore')

Before drop the given dataset

In [4]:
data.head()

Unnamed: 0       Date  Label  \
0        1988   7/1/2016      1   
1        1987  6/30/2016      1   
2        1986  6/29/2016      1   
3        1985  6/28/2016      1   
4        1984  6/27/2016      0   

                                                Top1  \
0  A 117-year-old woman in Mexico City finally re...   
1  Jamaica proposes marijuana dispensers for tour...   
2                   Explosion At Airport In Istanbul   
3  2,500 Scientists To Australia: If You Want To ...   
4  Barclays and RBS shares suspended from trading...   

                                                Top2  \
0   IMF chief backs Athens as permanent Olympic host   
1  Stephen Hawking says pollution and 'stupidity'...   
2  Yemeni former president: Terrorism is the offs...   
3  The personal details of 112,000 French police ...   
4  Pope says Church should ask forgiveness from g...   

                                                Top3  \
0  The president of France says if Brexit won, so...   
1  Boris Johnson says he will not run for Tory pa...   
2  UK must accept freedom of movement to access E...   
3  S&amp;P cuts United Kingdom sovereign credit r...   
4  Poland 'shocked' by xenophobic abuse of Poles ...   

                                                Top4  \
0  British Man Who Must Give Police 24 Hours' Not...   
1  Six gay men in Ivory Coast were abused and for...   
2  Devastated: scientists too late to captive bre...   
3                Huge helium deposit found in Africa   
4  There will be no second referendum, cabinet ag...   

                                                Top5  \
0  100+ Nobel laureates urge Greenpeace to stop o...   
1  Switzerland denies citizenship to Muslim immig...   
2  British Labor Party leader Jeremy Corbyn loses...   
3  CEO of the South African state broadcaster qui...   
4      Scotland welcome to join EU, Merkel ally says   

                                                Top6  \
0  Brazil: Huge spike in number of police killing...   
1  Palestinian terrorist stabs israeli teen girl ...   
2  A Muslim Shop in the UK Was Just Firebombed Wh...   
3  Brexit cost investors $2 trillion, the worst o...   
4  Sterling dips below Friday's 31-year low amid ...   

                                                Top7  ...  \
0  Austria's highest court annuls presidential el...  ...   
1  Puerto Rico will default on $1 billion of debt...  ...   
2  Mexican Authorities Sexually Torture Women in ...  ...   
3  Hong Kong democracy activists call for return ...  ...   
4  No negative news about South African President...  ...   

                                               Top22  \
0  Spain arrests three Pakistanis accused of prom...   
1  US permitted 1,200 offshore fracks in Gulf of ...   
2  Google Found Disastrous Symantec and Norton Vu...   
3  "Romanians for Remainians" offering a new home...   
4  Conservative MP Leave Campaigner: "The leave c...   

                                               Top23  \
0  Venezuela, where anger over food shortages is ...   
1  We will be swimming in ridicule - French beach...   
2  Extremist violence on the rise in Germany: Dom...   
3  Brexit: Gibraltar in talks with Scotland to st...   
4  Economists predict UK recession, further weake...   

                                               Top24  \
0  A Hindu temple worker has been killed by three...   
1  UEFA says no minutes of silence for Istanbul v...   
2  BBC News: Labour MPs pass Corbyn no-confidence...   
3                   8 Suicide Bombers Strike Lebanon   
4  New EU 'superstate plan by France, Germany: Cr...   

                                               Top25  \
0  Ozone layer hole seems to be healing - US &amp...   
1  Law Enforcement Sources: Gun Used in Paris Ter...   
2  Tiny New Zealand town with 'too many jobs' lau...   
3  Mexico's security forces routinely use 'sexual...   
4  Pakistani clerics declare transgender marriage...   

                                                Para Su

In [5]:
#shape
data.shape

(1989, 34)

After drop the given dataset

In [6]:
df=data.dropna()

In [7]:
df.head()

Unnamed: 0       Date  Label  \
0        1988   7/1/2016      1   
1        1987  6/30/2016      1   
2        1986  6/29/2016      1   
3        1985  6/28/2016      1   
4        1984  6/27/2016      0   

                                                Top1  \
0  A 117-year-old woman in Mexico City finally re...   
1  Jamaica proposes marijuana dispensers for tour...   
2                   Explosion At Airport In Istanbul   
3  2,500 Scientists To Australia: If You Want To ...   
4  Barclays and RBS shares suspended from trading...   

                                                Top2  \
0   IMF chief backs Athens as permanent Olympic host   
1  Stephen Hawking says pollution and 'stupidity'...   
2  Yemeni former president: Terrorism is the offs...   
3  The personal details of 112,000 French police ...   
4  Pope says Church should ask forgiveness from g...   

                                                Top3  \
0  The president of France says if Brexit won, so...   
1  Boris Johnson says he will not run for Tory pa...   
2  UK must accept freedom of movement to access E...   
3  S&amp;P cuts United Kingdom sovereign credit r...   
4  Poland 'shocked' by xenophobic abuse of Poles ...   

                                                Top4  \
0  British Man Who Must Give Police 24 Hours' Not...   
1  Six gay men in Ivory Coast were abused and for...   
2  Devastated: scientists too late to captive bre...   
3                Huge helium deposit found in Africa   
4  There will be no second referendum, cabinet ag...   

                                                Top5  \
0  100+ Nobel laureates urge Greenpeace to stop o...   
1  Switzerland denies citizenship to Muslim immig...   
2  British Labor Party leader Jeremy Corbyn loses...   
3  CEO of the South African state broadcaster qui...   
4      Scotland welcome to join EU, Merkel ally says   

                                                Top6  \
0  Brazil: Huge spike in number of police killing...   
1  Palestinian terrorist stabs israeli teen girl ...   
2  A Muslim Shop in the UK Was Just Firebombed Wh...   
3  Brexit cost investors $2 trillion, the worst o...   
4  Sterling dips below Friday's 31-year low amid ...   

                                                Top7  ...  \
0  Austria's highest court annuls presidential el...  ...   
1  Puerto Rico will default on $1 billion of debt...  ...   
2  Mexican Authorities Sexually Torture Women in ...  ...   
3  Hong Kong democracy activists call for return ...  ...   
4  No negative news about South African President...  ...   

                                               Top22  \
0  Spain arrests three Pakistanis accused of prom...   
1  US permitted 1,200 offshore fracks in Gulf of ...   
2  Google Found Disastrous Symantec and Norton Vu...   
3  "Romanians for Remainians" offering a new home...   
4  Conservative MP Leave Campaigner: "The leave c...   

                                               Top23  \
0  Venezuela, where anger over food shortages is ...   
1  We will be swimming in ridicule - French beach...   
2  Extremist violence on the rise in Germany: Dom...   
3  Brexit: Gibraltar in talks with Scotland to st...   
4  Economists predict UK recession, further weake...   

                                               Top24  \
0  A Hindu temple worker has been killed by three...   
1  UEFA says no minutes of silence for Istanbul v...   
2  BBC News: Labour MPs pass Corbyn no-confidence...   
3                   8 Suicide Bombers Strike Lebanon   
4  New EU 'superstate plan by France, Germany: Cr...   

                                               Top25  \
0  Ozone layer hole seems to be healing - US &amp...   
1  Law Enforcement Sources: Gun Used in Paris Ter...   
2  Tiny New Zealand town with 'too many jobs' lau...   
3  Mexico's security forces routinely use 'sexual...   
4  Pakistani clerics declare transgender marriage...   

                                                Para Su

In [8]:
#shape
df.shape

(1986, 34)

In [9]:
#show columns
df.columns

Index(['Unnamed: 0', 'Date', 'Label', 'Top1', 'Top2', 'Top3', 'Top4', 'Top5',
       'Top6', 'Top7', 'Top8', 'Top9', 'Top10', 'Top11', 'Top12', 'Top13',
       'Top14', 'Top15', 'Top16', 'Top17', 'Top18', 'Top19', 'Top20', 'Top21',
       'Top22', 'Top23', 'Top24', 'Top25', 'Para', 'Subjectivity',
       'Objectivity', 'Positive', 'Neutral', 'Negative'],
      dtype='object')

In [10]:
#To describe the dataframe
df.describe()

Unnamed: 0        Label  Subjectivity  Objectivity     Positive  \
count  1986.000000  1986.000000   1986.000000  1986.000000  1986.000000   
mean    994.843907     0.534743     56.712522    43.287478    19.966718   
std     574.301065     0.498917     21.557927    21.557927    16.373424   
min       0.000000     0.000000      0.000000     0.000000     0.000000   
25%     498.250000     0.000000     40.000000    28.571429     8.333333   
50%     995.500000     1.000000     54.545455    45.454545    18.181818   
75%    1491.750000     1.000000     71.428571    60.000000    28.571429   
max    1988.000000     1.000000    100.000000   100.000000   100.000000   

           Neutral     Negative  
count  1986.000000  1986.000000  
mean     43.287478    36.745804  
std      21.557927    21.109970  
min       0.000000     0.000000  
25%      28.571429    21.859903  
50%      45.454545    33.333333  
75%      60.000000    50.000000  
max     100.000000   100.000000

In [11]:
del df['Unnamed: 0']

In [12]:
#Checking datatype and information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1986 entries, 0 to 1988
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Date          1986 non-null   object 
 1   Label         1986 non-null   int64  
 2   Top1          1986 non-null   object 
 3   Top2          1986 non-null   object 
 4   Top3          1986 non-null   object 
 5   Top4          1986 non-null   object 
 6   Top5          1986 non-null   object 
 7   Top6          1986 non-null   object 
 8   Top7          1986 non-null   object 
 9   Top8          1986 non-null   object 
 10  Top9          1986 non-null   object 
 11  Top10         1986 non-null   object 
 12  Top11         1986 non-null   object 
 13  Top12         1986 non-null   object 
 14  Top13         1986 non-null   object 
 15  Top14         1986 non-null   object 
 16  Top15         1986 non-null   object 
 17  Top16         1986 non-null   object 
 18  Top17         1986 non-null 

Checking duplicate values of dataframe

In [13]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1984    False
1985    False
1986    False
1987    False
1988    False
Length: 1986, dtype: bool

In [14]:
#find sum of duplicate data
sum(df.duplicated())

0

In [15]:
#Checking sum of missing values
df.isnull().sum()

Date            0
Label           0
Top1            0
Top2            0
Top3            0
Top4            0
Top5            0
Top6            0
Top7            0
Top8            0
Top9            0
Top10           0
Top11           0
Top12           0
Top13           0
Top14           0
Top15           0
Top16           0
Top17           0
Top18           0
Top19           0
Top20           0
Top21           0
Top22           0
Top23           0
Top24           0
Top25           0
Para            0
Subjectivity    0
Objectivity     0
Positive        0
Neutral         0
Negative        0
dtype: int64

In [16]:
df.Label.unique()

array([1, 0], dtype=int64)

In [17]:
df.Subjectivity.unique()

array([ 60.        , 100.        ,  80.        ,  42.85714286,
        33.33333333,  50.        ,  71.42857143,  66.66666667,
        75.        ,  55.55555556,  40.        ,  25.        ,
        87.5       ,  83.33333333,  57.14285714,  88.88888889,
         0.        ,  28.57142857,  62.5       ,  27.27272727,
        37.5       ,  20.        ,  85.71428571,  44.44444444,
        41.66666667,  36.36363636,  16.66666667,  14.28571429,
        77.77777778,  38.46153846,  54.54545455,  70.        ,
        30.        ,  63.63636364,  58.33333333,  61.53846154,
        45.45454545,  72.72727273,  43.75      ,  90.        ,
        41.17647059,   8.33333333,  46.66666667,  47.36842105,
        64.28571429,  53.84615385,  47.05882353,  22.22222222,
        30.76923077,  31.25      ,  35.71428571,  81.81818182,
        29.41176471,  35.29411765,  23.07692308,  46.15384615,
        53.33333333,  91.66666667,  26.66666667,  12.5       ,
        58.82352941,  42.10526316,  73.33333333,  26.31

In [18]:
df.Objectivity.unique()

array([ 40.        ,   0.        ,  20.        ,  57.14285714,
        66.66666667,  50.        ,  28.57142857,  33.33333333,
        25.        ,  44.44444444,  60.        ,  75.        ,
        12.5       ,  16.66666667,  42.85714286,  11.11111111,
       100.        ,  71.42857143,  37.5       ,  72.72727273,
        62.5       ,  80.        ,  14.28571429,  55.55555556,
        58.33333333,  63.63636364,  83.33333333,  85.71428571,
        22.22222222,  61.53846154,  45.45454545,  30.        ,
        70.        ,  36.36363636,  41.66666667,  38.46153846,
        54.54545455,  27.27272727,  56.25      ,  10.        ,
        58.82352941,  91.66666667,  53.33333333,  52.63157895,
        35.71428571,  46.15384615,  52.94117647,  77.77777778,
        69.23076923,  68.75      ,  64.28571429,  18.18181818,
        70.58823529,  64.70588235,  76.92307692,  53.84615385,
        46.66666667,   8.33333333,  73.33333333,  87.5       ,
        41.17647059,  57.89473684,  26.66666667,  73.68

In [19]:
df.Positive.unique()

array([  0.        , 100.        ,  16.66666667,  33.33333333,
        28.57142857,  22.22222222,  20.        ,  50.        ,
        60.        ,  37.5       ,  57.14285714,  25.        ,
        14.28571429,  40.        ,  44.44444444,  75.        ,
        12.5       ,  42.85714286,  58.33333333,  66.66666667,
        11.11111111,  18.18181818,  15.38461538,   9.09090909,
        10.        ,  45.45454545,  83.33333333,  27.27272727,
        30.        ,  36.36363636,  62.5       ,  41.66666667,
        13.33333333,  18.75      ,  30.76923077,  21.42857143,
        29.41176471,  23.07692308,  26.66666667,   6.66666667,
        36.84210526,   8.33333333,  55.55555556,   6.25      ,
         7.14285714,  17.64705882,  31.25      ,   5.88235294,
         7.69230769,  35.71428571,  11.76470588,   5.55555556,
        27.77777778,  15.78947368,  23.52941176,  10.52631579,
        38.46153846,   4.54545455,   5.26315789,  15.        ,
        26.08695652,  21.73913043,  46.15384615,  21.05

In [20]:
df.Neutral.unique()

array([ 40.        ,   0.        ,  20.        ,  57.14285714,
        66.66666667,  50.        ,  28.57142857,  33.33333333,
        25.        ,  44.44444444,  60.        ,  75.        ,
        12.5       ,  16.66666667,  42.85714286,  11.11111111,
       100.        ,  71.42857143,  37.5       ,  72.72727273,
        62.5       ,  80.        ,  14.28571429,  55.55555556,
        58.33333333,  63.63636364,  83.33333333,  85.71428571,
        22.22222222,  61.53846154,  45.45454545,  30.        ,
        70.        ,  36.36363636,  41.66666667,  38.46153846,
        54.54545455,  27.27272727,  56.25      ,  10.        ,
        58.82352941,  91.66666667,  53.33333333,  52.63157895,
        35.71428571,  46.15384615,  52.94117647,  77.77777778,
        69.23076923,  68.75      ,  64.28571429,  18.18181818,
        70.58823529,  64.70588235,  76.92307692,  53.84615385,
        46.66666667,   8.33333333,  73.33333333,  87.5       ,
        41.17647059,  57.89473684,  26.66666667,  73.68

In [21]:
df.Negative.unique()

array([ 60.        ,   0.        ,  80.        ,  42.85714286,
        16.66666667, 100.        ,  66.66666667,  50.        ,
        75.        ,  33.33333333,  20.        ,  25.        ,
        37.5       ,  40.        ,  57.14285714,  44.44444444,
        12.5       ,  14.28571429,  28.57142857,  71.42857143,
        27.27272727,  83.33333333,  18.18181818,  22.22222222,
        23.07692308,  45.45454545,  41.66666667,  70.        ,
        30.        ,  55.55555556,  10.        ,  11.11111111,
        46.15384615,  26.66666667,   7.69230769,   9.09090909,
        21.42857143,  11.76470588,  15.38461538,  30.76923077,
         8.33333333,  62.5       ,   6.66666667,  13.33333333,
        18.75      ,  10.52631579,  36.36363636,  54.54545455,
        31.25      ,  38.46153846,  29.41176471,  41.17647059,
        72.72727273,  85.71428571,  17.64705882,  23.52941176,
        27.77777778,  31.57894737,  35.29411765,  35.        ,
        35.71428571,  26.31578947,   7.14285714,  46.66

To validate Age of patients:

In [22]:
print("Minimum value of Subjectivity of News is:", df.Subjectivity.min())
print("Maximum value of Subjectivity of News is:", df.Subjectivity.max())

Minimum value of Subjectivity of News is: 0.0
Maximum value of Subjectivity of News is: 100.0


In [23]:
print("News of Subjectivity ranges :", sorted(df['Subjectivity'].unique()))

News of Subjectivity ranges : [0.0, 6.666666667, 8.333333333, 9.090909091, 12.5, 13.33333333, 14.28571429, 15.78947368, 16.66666667, 18.18181818, 18.75, 19.04761905, 20.0, 21.05263158, 21.42857143, 21.73913043, 22.22222222, 22.5, 22.72727273, 23.07692308, 23.52941176, 23.80952381, 24.0, 25.0, 26.31578947, 26.66666667, 26.92307692, 27.27272727, 27.5862069, 27.77777778, 28.0, 28.57142857, 29.03225806, 29.16666667, 29.41176471, 30.0, 30.43478261, 30.76923077, 31.25, 31.57894737, 31.81818182, 32.0, 33.33333333, 34.61538462, 34.7826087, 35.0, 35.29411765, 35.71428571, 36.0, 36.36363636, 36.84210526, 37.03703704, 37.5, 38.0952381, 38.46153846, 38.70967742, 38.88888889, 39.28571429, 40.0, 40.90909091, 41.17647059, 41.66666667, 42.10526316, 42.30769231, 42.85714286, 43.47826087, 43.75, 44.0, 44.44444444, 44.82758621, 45.0, 45.45454545, 45.83333333, 46.15384615, 46.66666667, 47.05882353, 47.36842105, 47.61904762, 47.82608696, 48.0, 50.0, 52.17391304, 52.38095238, 52.63157895, 52.94117647, 53.33

In [24]:
p.Categorical(df['Subjectivity']).describe()

counts     freqs
categories                   
0.0               2  0.001007
6.666666667       1  0.000504
8.333333333       2  0.001007
9.090909091       1  0.000504
12.5              2  0.001007
...             ...       ...
88.88888889       5  0.002518
90.0              2  0.001007
91.66666667       1  0.000504
92.85714286       1  0.000504
100.0           185  0.093152

[121 rows x 2 columns]

In [25]:
p.Categorical(df['Objectivity']).describe()

counts     freqs
categories                   
0.0             185  0.093152
7.142857143       1  0.000504
8.333333333       1  0.000504
10.0              2  0.001007
11.11111111       5  0.002518
...             ...       ...
87.5              2  0.001007
90.90909091       1  0.000504
91.66666667       2  0.001007
93.33333333       1  0.000504
100.0             2  0.001007

[121 rows x 2 columns]

In [26]:
df['Label'].value_counts()

1    1062
0     924
Name: Label, dtype: int64

In [27]:
df.corr()

Label  Subjectivity  Objectivity  Positive   Neutral  \
Label         1.000000     -0.009935     0.009935  0.003905  0.009935   
Subjectivity -0.009935      1.000000    -1.000000  0.406829 -1.000000   
Objectivity   0.009935     -1.000000     1.000000 -0.406829  1.000000   
Positive      0.003905      0.406829    -0.406829  1.000000 -0.406829   
Neutral       0.009935     -1.000000     1.000000 -0.406829  1.000000   
Negative     -0.013174      0.705674    -0.705674 -0.360164 -0.705674   

              Negative  
Label        -0.013174  
Subjectivity  0.705674  
Objectivity  -0.705674  
Positive     -0.360164  
Neutral      -0.705674  
Negative      1.000000

Before Pre-Processing:

In [28]:
df.head()

Date  Label                                               Top1  \
0   7/1/2016      1  A 117-year-old woman in Mexico City finally re...   
1  6/30/2016      1  Jamaica proposes marijuana dispensers for tour...   
2  6/29/2016      1                   Explosion At Airport In Istanbul   
3  6/28/2016      1  2,500 Scientists To Australia: If You Want To ...   
4  6/27/2016      0  Barclays and RBS shares suspended from trading...   

                                                Top2  \
0   IMF chief backs Athens as permanent Olympic host   
1  Stephen Hawking says pollution and 'stupidity'...   
2  Yemeni former president: Terrorism is the offs...   
3  The personal details of 112,000 French police ...   
4  Pope says Church should ask forgiveness from g...   

                                                Top3  \
0  The president of France says if Brexit won, so...   
1  Boris Johnson says he will not run for Tory pa...   
2  UK must accept freedom of movement to access E...   
3  S&amp;P cuts United Kingdom sovereign credit r...   
4  Poland 'shocked' by xenophobic abuse of Poles ...   

                                                Top4  \
0  British Man Who Must Give Police 24 Hours' Not...   
1  Six gay men in Ivory Coast were abused and for...   
2  Devastated: scientists too late to captive bre...   
3                Huge helium deposit found in Africa   
4  There will be no second referendum, cabinet ag...   

                                                Top5  \
0  100+ Nobel laureates urge Greenpeace to stop o...   
1  Switzerland denies citizenship to Muslim immig...   
2  British Labor Party leader Jeremy Corbyn loses...   
3  CEO of the South African state broadcaster qui...   
4      Scotland welcome to join EU, Merkel ally says   

                                                Top6  \
0  Brazil: Huge spike in number of police killing...   
1  Palestinian terrorist stabs israeli teen girl ...   
2  A Muslim Shop in the UK Was Just Firebombed Wh...   
3  Brexit cost investors $2 trillion, the worst o...   
4  Sterling dips below Friday's 31-year low amid ...   

                                                Top7  \
0  Austria's highest court annuls presidential el...   
1  Puerto Rico will default on $1 billion of debt...   
2  Mexican Authorities Sexually Torture Women in ...   
3  Hong Kong democracy activists call for return ...   
4  No negative news about South African President...   

                                                Top8  ...  \
0  Facebook wins privacy case, can track any Belg...  ...   
1  Republic of Ireland fans to be awarded medal f...  ...   
2            UK shares and pound continue to recover  ...   
3  Brexit: Iceland president says UK can join 'tr...  ...   
4  Surge in Hate Crimes in the U.K. Following U.K...  ...   

                                               Top22  \
0  Spain arrests three Pakistanis accused of prom...   
1  US permitted 1,200 offshore fracks in Gulf of ...   
2  Google Found Disastrous Symantec and Norton Vu...   
3  "Romanians for Remainians" offering a new home...   
4  Conservative MP Leave Campaigner: "The leave c...   

                                               Top23  \
0  Venezuela, where anger over food shortages is ...   
1  We will be swimming in ridicule - French beach...   
2  Extremist violence on the rise in Germany: Dom...   
3  Brexit: Gibraltar in talks with Scotland to st...   
4  Economists predict UK recession, further weake...   

                                               Top24  \
0  A Hindu temple worker has been killed by three...   
1  UEFA says no minutes of silence for Istanbul v...   
2  BBC News: Labour MPs pass Corbyn no-confidence...   
3                   8 Suicide Bombers Strike Lebanon   
4  New EU 'superstate plan by France, Germany: Cr...   

                                               Top25  \
0  Ozone layer hole seems to be healing - US &amp...   
1  Law Enforcement Sources: Gun Used in Paris Ter..

After Pre-Processing:

In [29]:
df.columns

Index(['Date', 'Label', 'Top1', 'Top2', 'Top3', 'Top4', 'Top5', 'Top6', 'Top7',
       'Top8', 'Top9', 'Top10', 'Top11', 'Top12', 'Top13', 'Top14', 'Top15',
       'Top16', 'Top17', 'Top18', 'Top19', 'Top20', 'Top21', 'Top22', 'Top23',
       'Top24', 'Top25', 'Para', 'Subjectivity', 'Objectivity', 'Positive',
       'Neutral', 'Negative'],
      dtype='object')

In [30]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['Date', 'Label', 'Top1', 'Top2', 'Top3', 'Top4', 'Top5', 'Top6', 'Top7',
       'Top8', 'Top9', 'Top10', 'Top11', 'Top12', 'Top13', 'Top14', 'Top15',
       'Top16', 'Top17', 'Top18', 'Top19', 'Top20', 'Top21', 'Top22', 'Top23',
       'Top24', 'Top25', 'Para', 'Subjectivity', 'Objectivity', 'Positive',
       'Neutral', 'Negative']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(str)


ModuleNotFoundError: No module named 'sklearn'

In [ ]:
df.head()